// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TTS_Chan.Database;

namespace TTS_Chan.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220423022320_AddSubstitutions")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("TTS_Chan.Database.MessageSubstitution", b =>
                {
                    b.Property<int>("MessageSubstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRegex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("Replacement")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageSubstitutionId");

                    b.ToTable("MessageSubstitutions");
                });

            modelBuilder.Entity("TTS_Chan.Database.UserVoice", b =>
                {
                    b.Property<int>("UserVoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pitch")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("VoiceProvider")
                        .HasColumnType("TEXT");

                    b.HasKey("UserVoiceId");

                    b.ToTable("UserVoices");
                });
#pragma warning restore 612, 618
        }
    }
}
